### PR TITLE
Feat: castelo branco ug

### PR DESCRIPTION
**Pull request by mmuller88**

### CODE REVIEW

**Comment by tigpt** [comment]
Hi @mmuller88 

Ty for your PR.

The key of the object will be used to create the subdomain.

Just to confirm before aprove, do you want the subdomain to be `castelo_branco.awsug.site` like it is now or do you want to change the underscore with something else ?

Thanks.

**Comment by mmuller88** [comment]
@mmuller88 good point that was a mistake actually. I'll fix it

**Review by tigpt — APPROVED** [review]
Looks good! Thanks

**Comment by tigpt** [comment]
Up and running 

```
dig ns castelo-branco.awsug.site
castelo-branco.awsug.site. 172795 IN	NS	ns-975.awsdns-57.net.
castelo-branco.awsug.site. 172795 IN	NS	ns-1724.awsdns-23.co.uk.
castelo-branco.awsug.site. 172795 IN	NS	ns-158.awsdns-19.com.
castelo-branco.awsug.site. 172795 IN	NS	ns-1146.awsdns-15.org.
```

**Pull request merged**
